project:
  type: website
  output-dir: docs


website:
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: talks.qmd
        text: Talks
      - href: notes.qmd
        text: Notes
    right:
    - icon: github
      href: www.github.com/vdutor
    - icon: twitter
      href: www.github.com/vdutor
  twitter-card:
     creator: "@vdutor"
  site-url: "https://vdutor.github.io/"

  search: false

format:
  html:
    theme: 
      light:
        - simplex
        - custom.scss
    linkcolor: blue
    css:
      - styles.css
    toc: true