project:
  type: website
  output-dir: docs


website:
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: talks
        text: Talks
      - href: notes
        text: Notes
  twitter-card:
     creator: "@vdutor"
  site-url: "https://vdutor.github.io/"
  page-footer:
    center: "Last updated on 19 Jun 2023"
      

  search: false

format:
  html:
    theme: 
      light:
        - simplex
        - custom.scss
    linkcolor: blue
    css:
      - styles.css
    toc: true